services:
  mysql:
    build: ./MySql/
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - mysql_data:/var/lib/mysql/data
    networks:
      - app-net
    
  pythonapp:
    build: ./Python/
    command: sh -c "sleep 20s ; python3 ./app.py"
    depends_on:
      - mysql
    networks:
      - app-net


  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - pythonapp
    networks:
      - app-net
volumes:
  mysql_data:
networks:
  app-net:
    driver: bridge